---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ~/containers/qbittorrent/appdata:/config
      - /mnt/data/torrents:/downloads #optional
#    ports:
      # - 8080:8080
      # - 6881:6881
      # - 6881:6881/udp
    restart: unless-stopped
